module.exports = {
    printWidth: 150,
    tabWidth: 4,
    tabs: false,
    semi: true,
    singleQuote: true,
    quoteProps: 'as-needed',
    jsxSingleQuote: true,
    trailingComma: 'es5',
    bracketSpacing: true,
    bracketSameLine: true,
    arrowParens: 'always',
    insertPragma: false,
    proseWrap: 'preserve',
    endOfLine: 'lf',
    embeddedLanguageFormatting: 'auto',
};
